// <auto-generated />
namespace CannyStore.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class OrderMi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderMi));
        
        string IMigrationMetadata.Id
        {
            get { return "202310110702250_OrderMi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
